#pragma once
#include <QtCore/qstring.h>
#include <QtCore/qmap.h>

/**
  * Abstract class for procedural model generation.
  */
class AbstractModelBuilder
{
protected:
	/**
	  * Name of shape generated by this model generator.
	  */
	QString modelType;

	/**
	  * Parameters used for model generation.
	  */
	QMap<QString, void*> parameters;
public:

	/**
	  * \brief Default constructor.
	  */
	AbstractModelBuilder();

	/**
	  * \brief Default destructor.
	  */
	~AbstractModelBuilder();

	/**
	  * \brief Gets name of shape generated by this model generator.
	  *
	  * @return Name of shape generated by this model generator.
	  */
	QString getModelType();

	/**
	  * \brief Sets value of chosen parameter.
	  *
	  * @param name Name of parameter to change.
	  * @param value New value for parameter.
	  */
	void setParameter(QString name, void* value);

	/**
	  * \brief Creates model using set parameters.
	  *
	  * Creates model using set parameters and adds it to model manager.
	  * @return Generated model.
	  */
	virtual class Model* Build() = 0;

	/**
	  * \brief Resets values of parameters.
	  */
	virtual void resetParameters();
};

