#pragma once
#include <QtCore/qstring.h>
#include <QtCore/qhash.h>
#include <QtCore/qvariant.h>

namespace TropicalEngine
{

	#pragma region documentation
	/**
	  * \brief Abstract class for procedural model generation.
	  */
	#pragma endregion
	class AbstractModelBuilder
	{
	protected:
		#pragma region documentation
		/**
		  * Name of shape generated by this model generator.
		  */
		#pragma endregion
		QString modelType;

		#pragma region documentation
		/**
		  * Parameters used for model generation.
		  */
		#pragma endregion
		QVariantHash parameters;
	public:
		#pragma region documentation
		/**
		  * \brief Default constructor.
		  */
		#pragma endregion
		AbstractModelBuilder();
		#pragma region documentation
		/**
		  * \brief Default destructor.
		  */
		#pragma endregion
		~AbstractModelBuilder();

		#pragma region documentation
		/**
		  * \brief Gets name of shape generated by this model generator.
		  *
		  * @return Name of shape generated by this model generator.
		  */
		#pragma endregion
		QString getModelType();

		#pragma region documentation
		/**
		  * \brief Sets value of chosen parameter.
		  *
		  * @param name Name of parameter to change.
		  * @param value New value for parameter.
		  */
		#pragma endregion
		void setParameter(QString name, QVariant value);

		#pragma region documentation
		/**
		  * \brief Creates model using set parameters.
		  *
		  * Creates model using set parameters and adds it to model manager.
		  * @return Generated model.
		  */
		#pragma endregion
		virtual class Model* Build() = 0;

		#pragma region documentation
		/**
		  * \brief Resets values of parameters.
		  */
		#pragma endregion
		virtual void resetParameters();
	};

}